### ISSUE TITLE
TypeError on step and window

### ISSUE THREAD

**Issue by EnzoAndree** [microgenomics/plotMyGBK#1]
When you run "the complete use"

`python plotMyGBK.py -f mygenbank.gbk -C Y -F Y -w 3000 -s 1500 -t 16`

plotMyGBK.py do not transform the values to integer.

Just replace the lines 448-450 with this

```
window = int(options.window)
step = int(options.step)
threads = int(options.threads)
```

Enzo.

**Comment by Sanrrone** [comment]
indeed, its safer, thanks Enzo
