### ISSUE TITLE
AttributeError: Values instance has no attribute 'cogoption'

### ISSUE THREAD

**Issue by fefasd** [microgenomics/plotMyGBK#3]
Hi S.!
I'm trying to run the script on the putida.gbk example (avalaible in this repository) but I'm getting this error
```
Traceback (most recent call last):
  File "plotMyGBK.py", line 479, in <module>
    main()
  File "plotMyGBK.py", line 445, in main
    makecog = options.cogoption
AttributeError: Values instance has no attribute 'cogoption'
```
I have Python v2.7.14, R v3.2.2

Also the folder for classify genes by function (on dropbox) is not available. I don't know if I need it for the script to work.

**Comment by Sanrrone** [comment]
Hi, this is a old version, try this one https://github.com/Sanrrone/plotMyGBK, is also old but newer with several changes.

**Comment by fefasd** [comment]
Thanks a lot!

**Comment by fefasd** [comment]
Hi again,
I'm trying the new version, but now I have this error
I don't know what I'm doing wrong
I'm using Windows Subsystem for Linux (WSL), R(v3.2.2) and Python2.7 (Pandas and Biopython installed)

```
python plotMyGBK.py -f putida.gbk
Traceback (most recent call last):
  File "plotMyGBK.py", line 5062, in <module>
    main()
  File "plotMyGBK.py", line 5024, in main
    gbkname=genbank_file.replace("/"," ").split()[len(genbank_file.replace("/"," ").split())-1]
AttributeError: 'NoneType' object has no attribute 'replace'
```
Please help me :(

**Comment by Sanrrone** [comment]
Hi,
you are doing nothing wrong, I notice the flag -f is for other thing, I already fix it, try again (download again for newer version), https://github.com/Sanrrone/plotMyGBK

**Comment by fefasd** [comment]
Thank you! Is working now!
